meta_product_name: "Agapay"
meta_title: "Agapay - Give. Differently"
meta_description: "Donate in just one click to causes that matter to you"
meta_image: "cover.png"                       # should exist in `app/assets/images/`
